# Generated by Django 2.1.1 on 2018-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordem',
            fields=[
                ('numero_id', models.AutoField(primary_key=True, serialize=False)),
                ('Os_numero', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
