# Generated by Django 2.1.1 on 2018-09-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='numero',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
